theme: jekyll-theme-minimal  # Usa el tema mínimo de Jekyll, que es limpio y sencillo
title: "Mi Blog"
description: "Blog personal sobre mis pasatiempos, viajes, y arte"
url: "https://tu-usuario.github.io/mi-blog"  # Cambia "tu-usuario" por tu nombre de usuario en GitHub
